### PR TITLE
[WIP] Update Caminus project to Django 1.7

### PR DESCRIPTION
**Pull request by asmallteapot**
**DO NOT MERGE** – This will run locally, but _is not ready to deploy_.

TODO:
- [ ] Re-enable API
  - [ ] Port from piston to [django-rest-framework](http://www.django-rest-framework.org) or [tastypie](http://tastypieapi.org)
  - [ ] Fix call to `api.events.user_message` in `badges.models.Award.save`
- [ ] Re-enable notifications context: `local.context.notifications`
- [ ] Test public-facing website
- [ ] Test admin functions
- [x] Add `.travis.yml` file.
- [ ] Fix test runner for Travis CI.

### CODE REVIEW

**Comment by tdfischer** [comment]
Seems travis is convinced this is a ruby project. As long as current tests pass, LGTM :+1:

**Comment by asmallteapot** [comment]
```
WARNING: We were unable to find a .travis.yml file. This may not be what you
  want. Build will be run with default settings.
```

Welp. I’ll add that to the TODO list.

**Comment by tdfischer** [comment]
Already added it: https://trello.com/c/C1a14PRa

**Comment by tdfischer** [comment]
can you push this branch to the caminus upstream repository so it can get circle-ci testing? I'm keen to try that along with travis.

**Pull request closed without merging**
